### ISSUE TITLE
Persistent EJB timers not restored after Docker container restart

### ISSUE THREAD

**Issue by g-manfredi** [payara/docker-payaramicro#48] opened 2019-07-23 11:52 UTC
Hi everyone,

I have the following use case: I'm running my application on Payara Micro instances in Docker containers in a Kubernetes cluster. My application has persistent EJB timers. When a container restart happens (which I simulate outside of the cluster by running `docker-compose restart sample-service`), I expect these timers to be restored.
The timers are correctly found by the application server on startup, however they are not restored. After digging into the source code of Payara, I found out the reason: the restoration is skipped because the EJB container IDs of the bean don't match.

This happens at `fish.payara.ejb.timer.hazelcast.HazelcastTimerStore._restoreTimers(HazelcastTimerStore:962)` (in payara-server-5.183). 

If you want to try for yourself, I've created a sample project: https://github.com/g-manfredi/persistent-timers

Am I missing something? Is the setup not correct? Or is this an issue when running Payara in Docker? Thanks in advance for any support.

Setup of local testing (outside of the cluster):
* Payara Micro: 5.183
* Docker for Windows: Version 17.09.0-ce-win33 (13620)
* Windows 10

**Comment by OndroMih** [comment] 2019-07-24 09:46
Hi. This is a bug in Payara Micro 5. I tested your reproducer with Payara Micro 4.1.2.181 where the timer is restored after service restart. But it doesn't work with Payara Micro 5.183, 5.192 or 5.181.

This is not specific to Docker, it can be reproduced also by running 2 Payara Micro instances locally. 

Please raise an issue on the https://github.com/payara/Payara repo stating that the behavior works in 4.1.2.181 but not in Payara Micro 5.x at least since 5.181. I'm closing this issue but make sure you link to this issue from the new one.

**Closed by OndroMih** 2019-07-24 09:46 UTC
